
package wsClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchFileException", targetNamespace = "http://wsRemoteFileServer/")
public class NoSuchFileException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchFileException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoSuchFileException_Exception(String message, NoSuchFileException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoSuchFileException_Exception(String message, NoSuchFileException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsClient.NoSuchFileException
     */
    public NoSuchFileException getFaultInfo() {
        return faultInfo;
    }

}
