
package wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapRemoteFileServerService", targetNamespace = "http://wsRemoteFileServer/", wsdlLocation = "http://192.168.1.135:8080/a@b?wsdl")
public class SoapRemoteFileServerService
    extends Service
{

    private final static URL SOAPREMOTEFILESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPREMOTEFILESERVERSERVICE_EXCEPTION;
    private final static QName SOAPREMOTEFILESERVERSERVICE_QNAME = new QName("http://wsRemoteFileServer/", "SoapRemoteFileServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.135:8080/a@b?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPREMOTEFILESERVERSERVICE_WSDL_LOCATION = url;
        SOAPREMOTEFILESERVERSERVICE_EXCEPTION = e;
    }

    public SoapRemoteFileServerService() {
        super(__getWsdlLocation(), SOAPREMOTEFILESERVERSERVICE_QNAME);
    }

    public SoapRemoteFileServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPREMOTEFILESERVERSERVICE_QNAME, features);
    }

    public SoapRemoteFileServerService(URL wsdlLocation) {
        super(wsdlLocation, SOAPREMOTEFILESERVERSERVICE_QNAME);
    }

    public SoapRemoteFileServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPREMOTEFILESERVERSERVICE_QNAME, features);
    }

    public SoapRemoteFileServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapRemoteFileServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapRemoteFileServer
     */
    @WebEndpoint(name = "SoapRemoteFileServerPort")
    public SoapRemoteFileServer getSoapRemoteFileServerPort() {
        return super.getPort(new QName("http://wsRemoteFileServer/", "SoapRemoteFileServerPort"), SoapRemoteFileServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapRemoteFileServer
     */
    @WebEndpoint(name = "SoapRemoteFileServerPort")
    public SoapRemoteFileServer getSoapRemoteFileServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsRemoteFileServer/", "SoapRemoteFileServerPort"), SoapRemoteFileServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPREMOTEFILESERVERSERVICE_EXCEPTION!= null) {
            throw SOAPREMOTEFILESERVERSERVICE_EXCEPTION;
        }
        return SOAPREMOTEFILESERVERSERVICE_WSDL_LOCATION;
    }

}
